### ISSUE TITLE
[Bug] Column data must be provided as an instance of yii\db\ColumnSchemaBuilder.

### ISSUE THREAD

**Issue by sourabh-openinfotech** [bizley/yii2-migration#132] opened 2021-04-12 10:07 UTC
**Describe the bug**

Am getting the above error. I am trying to update migration for a certain table.

**Expected behavior**
The update migration to be created

**Additional context**
The create table migration 

```use yii\db\Migration;

class m201028_102051_076_create_table_client_invoice_item_table extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%client_invoice_item_table}}',
            [
                'id' => $this->primaryKey(),
                'description' => $this->string(250)->notNull(),
                'hsn_id' => $this->integer()->notNull(),
                'status' => $this->integer()->notNull()->defaultValue('0'),
                'width' => $this->double()->notNull(),
                'height' => $this->double()->notNull(),
                'amount' => $this->double(),
                'quantity' => $this->double(),
                'rate' => $this->double(),
                'client_invoice_master_id' => $this->integer()->notNull(),
                'created_by' => $this->integer()->notNull(),
                'created_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
                'updated_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
            ],
            $tableOptions
        );

        $this->createIndex('client_invoice_item_table_client_invoice_idx', '{{%client_invoice_item_table}}', ['client_invoice_master_id']);
        $this->createIndex('hsn_id', '{{%client_invoice_item_table}}', ['hsn_id']);
        $this->createIndex('created_by', '{{%client_invoice_item_table}}', ['created_by']);

        $this->addForeignKey(
            'client_invoice_item_table_ibfk_1',
            '{{%client_invoice_item_table}}',
            ['client_invoice_master_id'],
            '{{%client_invoice_master}}',
            ['id'],
            'RESTRICT',
            'RESTRICT'
        );

        $this->addForeignKey(
            'client_invoice_item_table_ibfk_3',
            '{{%client_invoice_item_table}}',
            ['hsn_id'],
            '{{%owner_hsn_master}}',
            ['id'],
            'RESTRICT',
            'RESTRICT'
        );
    }

    public function down()
    {
        $this->dropTable('{{%client_invoice_item_table}}');
    }
}
```
The related table migrations client_invoice_master

```
<?php

use yii\db\Migration;

class m201028_102051_070_create_table_client_invoice_master extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%client_invoice_master}}',
            [
                'id' => $this->primaryKey(),
                'invoice_no' => $this->string(45),
                'client_id' => $this->integer()->notNull(),
                'job_card_master_id' => $this->integer()->notNull(),
                'client_order_id' => $this->integer(),
                'order_reference' => $this->string(50),
                'invoice_to' => $this->string(100),
                'client_delivery_challan_id' => $this->integer(),
                'date' => $this->date()->notNull(),
                'client_order_date' => $this->date(),
                'dc_date' => $this->dateTime(),
                'description' => $this->string(),
                'email_message' => $this->text(),
                'note' => $this->string(500),
                'reference_name' => $this->string(50),
                'status' => $this->integer()->notNull()->defaultValue('0'),
                'discount' => $this->double(),
                'tax_type' => $this->integer()->notNull(),
                'cgst' => $this->string(45),
                'sgst' => $this->string(45),
                'igst' => $this->string(45),
                'add_signature' => $this->smallInteger()->defaultValue('0'),
                'created_by' => $this->integer()->notNull(),
                'created_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
                'updated_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
            ],
            $tableOptions
        );

        $this->createIndex('client_delivery_challan_id', '{{%client_invoice_master}}', ['client_delivery_challan_id']);
        $this->createIndex('fk_owner_invoice_master_owner_purchase_order1_idx', '{{%client_invoice_master}}', ['client_order_id']);
        $this->createIndex('tax_type', '{{%client_invoice_master}}', ['tax_type']);
        $this->createIndex('job_card_master_id', '{{%client_invoice_master}}', ['job_card_master_id']);
        $this->createIndex('client_id', '{{%client_invoice_master}}', ['client_id']);
        $this->createIndex('created_by', '{{%client_invoice_master}}', ['created_by']);

        $this->addForeignKey(
            'client_invoice_master_ibfk_5',
            '{{%client_invoice_master}}',
            ['client_id'],
            '{{%customer_company_details}}',
            ['id'],
            'RESTRICT',
            'RESTRICT'
        );
    }

    public function down()
    {
        $this->dropTable('{{%client_invoice_master}}');
    }
}
```
Another related table owner_hsn_master
```
<?php

use yii\db\Migration;

class m201028_102048_018_create_table_owner_hsn_master extends Migration
{
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%owner_hsn_master}}',
            [
                'id' => $this->primaryKey(),
                'hsn_mask' => $this->string(50)->notNull(),
                'hsn_code' => $this->string(50)->notNull(),
                'hsn_percentage' => $this->double()->notNull(),
                'status' => $this->integer(),
                'created_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
                'updated_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
            ],
            $tableOptions
        );
    }

    public function safeDown()
    {
        $this->dropTable('{{%owner_hsn_master}}');
    }
}


```

**Affected versions**
Version: 4.1

**Comment by bizley** [comment] 2021-04-12 12:37
Your migration looks good. Unfortunately I cannot repeat the bug with simple applying the above (I removed FK because I don't have the info about the related tables), changing something, and running `migration/update`. Could you provide the exact steps to reproduce your issue? With migrations for related tables and info about the database engine as well.

**Comment by sourabh-openinfotech** [comment] 2021-04-13 07:46
Using InnoDB Version 5.6.39-83.1. I have just migrated up, I think there is difference is some migrations  $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB'; which differs from current migration  $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB'; . Would this lead to error?

**Comment by bizley** [comment] 2021-04-13 08:31
I don't think so. That should not be a subject of comparison. Maybe there is something with that MySQL 5.6 version that causes the problem (it's 8 years old) - I'm testing this package on 5.7 and 8.0 only.

**Comment by sourabh-openinfotech** [comment] 2021-04-13 09:29
will try upgrading mysql version and see if it removes error

**Comment by sourabh-openinfotech** [comment] 2021-04-15 05:28
Upgrading mysql version did not solve the issue

**Comment by bizley** [comment] 2021-04-15 07:42
Ok, so my request stands. Exact steps to reproduce the issue with migrations for related tables.

**Comment by sourabh-openinfotech** [comment] 2021-04-15 09:43
Have included related table migrations

Steps to reproduce are:-
Through console (am on a windows machine),
1. running ./yii migrate/up(on production) or ./yii migrate/fresh(for development).  ✔️
2. running ./yii migration/update client_invoice_item_table  (after making width and height nullable in the actual database table, want this to be reflected in migration).  ❌

**Comment by bizley** [comment] 2021-04-15 11:21
I run the steps (except the `customer_company_details` table which definition is missing but it should not be a problem) and everything works. I ended with migration

```
<?php

use yii\db\Migration;

class m210415_105710_update_table_client_invoice_item_table extends Migration
{
    public function up()
    {
        $this->alterColumn('{{%client_invoice_item_table}}', 'width', $this->double());
        $this->alterColumn('{{%client_invoice_item_table}}', 'height', $this->double());
    }

    public function down()
    {
        $this->alterColumn('{{%client_invoice_item_table}}', 'width', $this->double()->notNull());
        $this->alterColumn('{{%client_invoice_item_table}}', 'height', $this->double()->notNull());
    }
}
```

Error message `Column data must be provided as an instance of yii\db\ColumnSchemaBuilder` pops up when you provide column definition as a string (like `'name' => 'varchar(255)'`) instead of an object (like `'name' => $this->string(255)`) and you don't set `experimental` (or `ex`) mode on. 

But I don't see it in your files here. I'm afraid I need to ask you to dig into this more in order to help. 
[$columnData](https://github.com/bizley/yii2-migration/blob/master/src/dummy/Migration.php#L187) info before it hits that line would be helpful.

**Comment by sourabh-openinfotech** [comment] 2021-04-15 12:21
> 
> 
> I run the steps (except the `customer_company_details` table which definition is missing but it should not be a problem) and everything works. I ended with migration
> 
> ```
> <?php
> 
> use yii\db\Migration;
> 
> class m210415_105710_update_table_client_invoice_item_table extends Migration
> {
>     public function up()
>     {
>         $this->alterColumn('{{%client_invoice_item_table}}', 'width', $this->double());
>         $this->alterColumn('{{%client_invoice_item_table}}', 'height', $this->double());
>     }
> 
>     public function down()
>     {
>         $this->alterColumn('{{%client_invoice_item_table}}', 'width', $this->double()->notNull());
>         $this->alterColumn('{{%client_invoice_item_table}}', 'height', $this->double()->notNull());
>     }
> }
> ```
> 
> Error message `Column data must be provided as an instance of yii\db\ColumnSchemaBuilder` pops up when you provide column definition as a string (like `'name' => 'varchar(255)'`) instead of an object (like `'name' => $this->string(255)`) and you don't set `experimental` (or `ex`) mode on.
> 
> But I don't see it in your files here. I'm afraid I need to ask you to dig into this more in order to help.
> [$columnData](https://github.com/bizley/yii2-migration/blob/master/src/dummy/Migration.php#L187) info before it hits that line would be helpful.

Thank you found the issue, one of the migrations had   'status' => "ENUM('Scheduled', 'Completed')" which was resulting in error. The error was so vague could't find anything on it.

**Comment by bizley** [comment] 2021-04-15 12:26
Great! Glad I could help. Can we close this then or should we do more here?

**Closed** 2021-04-16 06:06 UTC
Labels: bug
